### PR TITLE
responsiveness

### PR DESCRIPTION
**Pull request by i-am-gazali**
worked on the responsiveness

### CODE REVIEW

**Comment by niinortey** [comment]
Ok. Check out master. Do a pull/merge of upstream master. Check out the
branch you are currently working on. Do a merge of master into your current
branch. You may have some conflicts cos I made some heavy changes. Once you
resolve the conflicts and have a successful merge do a push of your current
branch to your origin. Then create a PR

**Comment by i-am-gazali** [comment]
Found no conflicts

**Comment by niinortey** [comment]
Did you already do the push to your origin? If so can you please create 
a PR (pull request).

**Comment by i-am-gazali** [comment]
#4 here it is

**Pull request merged**
